#!/bin/bash
IFS=

input=`zenity --text="How can I assist you?" --width=500 --entry`
if [ $input" " = " " ]
	then exit 1
fi
IFS=" " read cmd argument <<< $input
if [ $input = "specialis revelio" ]
then
	zenity --icon-name= --text="This program is the property of literal" --width=500 --info
else
	unset IFS
	dir="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
	fallback=$dir"/fallback $input"
	cmd=$dir"/modules/"$cmd".sh \"$argument\""
	echo $cmd > test
fi
$cmd || $fallback
